# -*- coding: utf-8 -*-
"""lec8_clustring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16B8z2P-MjVcqtIX_ADRWvBlUcU2krNzf

# Import the libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

"""# Import the data"""

data = pd.read_csv("D:\Courses\Data Science & ML by DotPy Academy\Week9_28.10.2022\Mall_Customers.csv")
data.head()

plt.scatter(data.iloc[:, 3:4], data.iloc[:, -1])
plt.show()

"""# taking the features"""

x = data.iloc[:, 3:5]
print(x)

"""# visualize the data"""

plt.scatter(x.iloc[:, 0:1], x.iloc[:, 1:2])

from sklearn.cluster import KMeans
WCSS = []
for i in range(1, 11):
    model = KMeans(n_clusters= i)
    model.fit(x)
    WCSS.append(model.inertia_)

print(WCSS)

"""# selecting the right number of clusters"""

plt.plot(range(1, 11), WCSS)



"""# applying the Kmeans clustring to the model"""

model = KMeans(n_clusters= 5)
model.fit(x)

y = model.fit_predict(x)

print(y)

"""# visualizing the final results"""

plt.scatter(x[y == 0, 0], x[y == 0, 1], c='red')
plt.scatter(x[y == 1, 0], x[y == 1, 1], c='black')
plt.scatter(x[y == 2, 0], x[y == 2, 1], c='g')
plt.scatter(x[y == 3, 0], x[y == 3, 1], c='y')
plt.scatter(x[y == 4, 0], x[y == 4, 1], c='m')
plt.show()

"""# deployment"""
#
# income = int(input("enter your income: "))
# spending = int(input("enter your spending score: "))
# new_point = [[income, spending]]
# your_group = clusters.predict(new_point)
# print(your_group)